apiVersion: v1
kind: Pod
metadata:
  name: fat-nginx
  namespace: demo
spec:
  containers:
  - name: apps
    image: nginx:latest
    resources:
      requests:
        cpu: "12" 
        memory: "1Gi"
      limits:
        cpu: "32" 
        memory: "2Gi"
