apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: my-deployment
  name: my-deployment
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: my-deployment
  type: ClusterIP
status:
  loadBalancer: {}
